#!/usr/bin/env python3

# usage: bin2h FILE ARRAY_NAME

import sys

fname = sys.argv[1]
array_name = sys.argv[2]

f = open(fname, "rb")
data = f.read()
f.close()

name = fname[:fname.index(".")]

print(f"const char {array_name}[{len(data)}] = {{", end="")

for i in range(len(data)):
    if i & 0x0f == 0:
        print("\n\t", end="")
    print(f"0x{data[i]:02X}", end="")
    if i < len(data)-1: print(", ", end="")

print("\n};")
